# docker-compose to run e2e tests
version: '2'
services:
  angular:
    image: node:12-alpine
    ports:
      - 4200
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PROTRACTOR_SELENIUM_ADDRESS: http://chrome:4444/
      # This doesn't work though this overrides `baseUrl` in proctractor.conf.js
      # as overridden with dev-server-target.
      PROTRACTOR_BASE_URL: http://angular:4200/
    command:
      - /bin/sh
      - -x
      - -c
      - |
        # --base-url=http://angular:4200/ causes a following error:
        #   The 'baseUrl' option cannot be used with 'devServerTarget'.
        # See https://github.com/angular/angular-cli/pull/13614
        #
        # --public-host=angular:4200 results `Unknown option: '--public-host'`
        #
        # protractor-docker.conf.js is to use headless chrome in docker
        ( [ -d node_modules ] || npm install ) \
        && npm run e2e -- \
          --host=0.0.0.0 \
          --port=4200 \
          --protractor-config=e2e/protractor-docker.conf.js
    depends_on:
      - chrome
    networks:
      - default
  chrome:
    build:
      context: .
      dockerfile: Dockerfile.chrome
    ports:
      - 4444
    networks:
      - default
    command:
      - chromedriver
      - --port=4444
      - --url-base=/
      # this means to accept external connections
      - --whitelisted-ips=
      - --verbose
